# Generated by Django 4.2.29 on 2026-03-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hopvariety',
            name='unique_variety_per_member',
        ),
    ]
