# Generated by Django 4.2.29 on 2026-03-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_hopvariety_unique_variety_per_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yieldrecord',
            name='quantity_kg',
            field=models.DecimalField(decimal_places=5, help_text='Yield in kilograms', max_digits=15),
        ),
    ]
