# Generated by Django 4.2.29 on 2026-03-10 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_yieldrecord_quantity_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopvariety',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hop_varieties', to='members.memberprofile'),
        ),
        migrations.AlterField(
            model_name='yieldrecord',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yield_records', to='members.memberprofile'),
        ),
    ]
