# Generated by Django 4.2.29 on 2026-03-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_hopvariety_member_alter_yieldrecord_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='start_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year the member started growing hops', null=True),
        ),
    ]
